### ISSUE TITLE
The MacAddressNodeIdentifier.findViableMacAddress() isn't always giving us the right MAC address

### ISSUE THREAD

**Issue by matshenricson** [charithe/flake4j#3]
We found that for some NetworkInterface objects, in this case on OsX, it was up, not a loopback, but still had a null MAC address (it was a tunnel). We suggest adding this extra if-statement around the return statement:

```
      if (!currentNic.isLoopback() && currentNic.isUp()) {
        byte[] macAddress = currentNic.getHardwareAddress();
        if (macAddress != null) {
          return Optional.of(macAddress);
        }
      }
```

**Comment by matshenricson** [comment]
We managed to get around the issue by copying the MacAddressNodeIdentifier class, tweaking the function as described above, and using an object of that class as parameter to `Flake4J.newInstance(NodeIdentifier nodeIdentifier)`

**Comment by charithe** [comment]
That's interesting. I am not sure why the additional null check is required because `Optional.of(null)` should be empty and hence throw an exception. If you have the ability to reproduce the issue, it would be brilliant if you could create a test case and send in a pull request.

**Comment by matshenricson** [comment]
Yes, Optional.of(null) would throw an exception, and that would make it not
consider other valid network interfaces that are returned later by the
enumeration.

Mats

**Comment by matshenricson** [comment]
Btw, we can only reproduce this on a Mac, so a generic unit test wouldn't
be of much use.

Mats

**Comment by charithe** [comment]
I see. Thanks for flagging it. I have fixed the loop to contiune until it finds a usable MAC address.

**Comment by matshenricson** [comment]
Thanks a lot! Our Mac user will now try to see if your fix works!

**Comment by matshenricson** [comment]
It doesn't seem to be pushed to central repositories yet.

**Comment by charithe** [comment]
I can see 1.0.2 in the Sonatype repo: https://oss.sonatype.org/#nexus-search;quick~flake4j

**Comment by matshenricson** [comment]
We'll have a look!
